---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: apiv1-deploy
  namespace: api-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      name: apiv1-po
  template:
    metadata:
      labels:
        name: apiv1-po
    spec:
      containers:
      - name: apiv1-container
        image: chukmunnlee/fake-api:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: apiv1-svc
  namespace: api-ns
spec:
  type: ClusterIP
  selector:
    name: apiv1-po
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: apiv2-deploy
  namespace: api-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      name: apiv2-po
  template:
    metadata:
      labels:
        name: apiv2-po
    spec:
      containers:
      - name: apiv2-container
        image: chukmunnlee/fake-api:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: apiv2-svc
  namespace: api-ns
spec:
  type: ClusterIP
  selector:
    name: apiv2-po
  ports:
  - port: 3000
    targetPort: 3000
