---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- countingbook.yaml

configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform-kustomize-v5.yaml

images:
- name: registry.gitlab.com/soda9105822/countingbook
  newTag: a5aedc71
