ARG VERSION=25

FROM node:${VERSION}

WORKDIR /app

COPY *.json .
COPY *.js .

RUN npm ci

ENV PORT=3000 OTEL_PORT=9464
ENV API_VERSION="v2" 

EXPOSE ${PORT} ${OTEL_PORT}

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD curl localhost:${PORT}/healthz || exit 1

SHELL [ "/bin/sh", "-c" ]

ENTRYPOINT node main.js 

