---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
  namespace: bgg-ns
  labels:
    app: bgg
    name: bgg-secret
type: Opaque
data:
  # hellohello
  MYSQL_ROOT_PASSWORD: aGVsbG9oZWxsbw==
  BGG_DB_PASSWORD: aGVsbG9oZWxsbw==
