---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bggapp-deploy
  name: bggapp-deploy
  namespace: bggns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bggapp-deploy
  template:
    metadata:
      labels:
        app: bggapp-deploy
    spec:
      containers:
      - image: chukmunnlee/bgg-app:nov-2025
        name: bgg-app
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
        ports:
        - containerPort: 5000
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 30
          httpGet:
            path: /healthz
            port: 5000
        resources:
          requests:
            memory: 96Mi
            cpu: 65m
          limits:
            memory: 96Mi
            cpu: 65m

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bggapp-deploy
  name: bggapp-svc
  namespace: bggns
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: bggapp-deploy
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bggapp-ing
  namespace: bggns
spec:
  ingressClassName: nginx 
  rules:
  - host: bgg-192.168.39.16.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bggapp-svc
            port:
              number: 5000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bggapp-hpa
  namespace: bggns
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bggapp-deploy
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
