---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-hsvc
  namespace: bgg-ns
  labels:
    app: bgg
    name: bggdb-hsvc
spec:
  clusterIP: None
  selector:
    app: bgg
    name: bggdb-po
  ports:
  - name: bggdb-port
    port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bggdb-sts
  namespace: bgg-ns
  labels:
    app: bgg
    name: bggdb-sts
spec:
  replicas: 1
  serviceName: bggdb-hsvc
  selector:
    matchLabels:
      app: bgg
      name: bggdb-po
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data-vol
    spec:
      storageClassName: standard
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      name: bggdb-po
      labels:
        app: bgg
        name: bggdb-po
    spec:
      containers:
      - name: bggdb-container
        image: chukmunnlee/bgg-database:v3.1
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: bgg-secret
        ports:
        - name: bggdb-port 
          containerPort: 3306
        volumeMounts:
        - name: data-vol
          mountPath: /var/lib/mysql

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bgg-ns
  labels: 
    app: bgg
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bggdb-po
  ports:
  - port: 3306
    targetPort: bggdb-port

