---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bggdb-pvc
  namespace: bggns
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bggdb-deploy
  name: bggdb-deploy
  namespace: bggns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bggdb-deploy
  template:
    metadata:
      labels:
        app: bggdb-deploy
    spec:
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: bggdb-pvc
      containers:
      - image: chukmunnlee/bgg-database:nov-2025
        name: bgg-database
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bgg-secret
              key: BGG_DB_PASSWORD

        volumeMounts:
        - name: data-vol
          mountPath: /var/lib/mysql

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bggdb-deploy
  name: bggdb-svc
  namespace: bggns
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: bggdb-deploy
  type: ClusterIP
